# Generated by Django 4.2.3 on 2023-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
        ),
    ]
